### ISSUE TITLE
Make it possible to set options through command line, without going through the interactive prompts

### ISSUE THREAD

**Issue by hagabaka** [raczak/crawlit-dofus-encyclopedia-parser#6]
For example, a user can run the program with `--game dofus --language english --category potions --all`.

**Comment by raczak** [comment]
Thanks to you @hagabaka for your contribution to this project ! I merged your pull request 👍

**Comment by Darkilen** [comment]
This didn't work for me. I test it on a new project as below.

```
git clone git@github.com:raczak/crawlit-dofus-encyclopedia-parser.git
cd crawlit-dofus-encyclopedia-parser/
npm i
./lib/app.js pets --game dofus-touch --language english --maxItem 1
```
This command has the same result as `.lib/app.js` or `npm start`

**Comment by Darkilen** [comment]
After some test, this works but the setup is really wierd.

This will output one pet for dofus-touch in english :
```
./lib/app.js weapon --category pet --game dofus-touch --language english --maxItem 1
```
But thoses will fail :

```
./lib/app.js --category pet --game dofus-touch --language english --maxItem 1
./lib/app.js pet --category pet --game dofus-touch --language english --maxItem 1
```

We need to set `weapon` or `equipment` in front of our parameters because of this [lib/cli-view/cmd.js#L156](https://github.com/raczak/crawlit-dofus-encyclopedia-parser/blob/master/lib/cli-view/cmd.js#L156) (here we have to define a category, but any) and this [lib/cli-view/cmd.js#L158](https://github.com/raczak/crawlit-dofus-encyclopedia-parser/blob/master/lib/cli-view/cmd.js#L158) (here, the option `-c , --category <CATEGORY>` is define only for `weapon` and `equipment` but is mandatory thereafter [lib/cli-view/cmd.js#L178)](https://github.com/raczak/crawlit-dofus-encyclopedia-parser/blob/master/lib/cli-view/cmd.js#L178)
